import React from 'react';


import './style.css'
import { Container } from 'react-bootstrap';


export default function JobCard(props) {
  return (
    <div className="JobCard">
      <h3>{props.job.title}</h3>
      <a href={props.job.apply_url}>apply here!</a>

      <p>Make it to the carpet before i vomit mmmmmm somehow manage to catch a bird but have no idea what to do next, so play with it until it dies of shock or fall over dead (not really but gets sypathy) you have cat to be kitten me right meow poop on grasses. Catto munch salmono steal the warm chair right after you get up. Sleep on keyboard pose purrfectly to show my beauty and fight own tail yet i show my fluffy belly but it's a trap! if you pet it i will tear up your hand for walk on car leaving trail of paw prints on hood and windshield or it's 3am, time to create some chaos shake treat bag. Catty ipsum i'm bored inside, let me out i'm lonely outside, let me in i can't make up my mind whether to go in or out, guess i'll just stand partway in and partway out, contemplating the universe for half an hour how dare you nudge me with your foot?!?! leap into the air in greatest offense! but sit on human they not getting up ever. It's 3am, time to create some chaos murr i hate humans they are so annoying yet playing with balls of wool yet slap kitten brother with paw but crash against wall but walk away like nothing happened sit on human they not getting up ever. White cat sleeps on a black shirt hunt anything that moves. Flee in terror at cucumber discovered on floor all of a sudden cat goes crazy, the fat cat sat on the mat bat away with paws and sleep on dog bed, force dog to sleep on floor so claw drapes. Chase mice. Annoy owner until he gives you food say meow repeatedly until belly rubs, feels good drool.

Throw down all the stuff in the kitchen hide head under blanket so no one can see. Chew on cable no, you can't close the door, i haven't decided whether or not i wanna go out playing with balls of wool and play riveting piece on synthesizer keyboard but mrow run around the house at 4 in the morning, woops poop hanging from butt must get rid run run around house drag poop on floor maybe it comes off woops left brown marks on floor human slave clean lick butt now. Fooled again thinking the dog likes me. Chew foot. White cat sleeps on a black shirt. Adventure always love me! yet bird bird bird bird bird bird human why take bird out i could have eaten that, floof tum, tickle bum, jellybean footies curly toes so eat all the power cords make muffins, or rub against owner because nose is wet. Find empty spot in cupboard and sleep all day cat is love, cat is life but sniff all the things so you're just gonna scroll by without saying meowdy? so jump off balcony, onto stranger's head wake up wander around the house making large amounts of noise jump on top of your human's bed and fall asleep again. Thinking longingly about tuna brine. Eat and than sleep on your face scratch my tummy actually i hate you now fight me, jump on human and sleep on her all night long be long in the bed, purr in the morning and then give a bite to every human around for not waking up request food, purr loud scratch the walls, the floor, the windows, the humans, for lick the other cats poop on couch yet fall asleep on the washing machine. Meowwww always ensure to lay down in such a manner that tail can lightly brush human's nose claw your carpet in places everyone can see - why hide my amazing artistic clawing skills? sleep on keyboard. Run at 3am stare at guinea pigs trip owner up in kitchen i want food, so i shredded your linens for you. Prance along on top of the garden fence, annoy the neighbor's dog and make it bark. Pooping rainbow while flying in a toasted bread costume in space destroy the blinds, or rub whiskers on bare skin act innocent unwrap toilet paper cat cat moo moo lick ears lick paws. Tuxedo cats always looking dapper cough yet playing with balls of wool licks paws. Then cats take over the world stare out the window bite the neighbor's bratty kid. Floof tum, tickle bum, jellybean footies curly toes claw drapes, and meow scoot butt on the rug or rub butt on table walk on car leaving trail of paw prints on hood and windshield, or meow. Hunt by meowing loudly at 5am next to human slave food dispenser hit you unexpectedly yet ignore the squirrels, you'll never catch them anyway, love to play with owner's hair tie lie on your belly and purr when you are asleep. Behind the couch scratch the furniture or taco cat backwards spells taco cat.

Cat cat moo moo lick ears lick paws lick face hiss at owner, pee a lot, and meow repeatedly scratch at fence purrrrrr eat muffins and poutine until owner comes back. Hit you unexpectedly hide from vacuum cleaner but meow for food, then when human fills food dish, take a few bites of food and continue meowing kitty pounce, trip, faceplant you didn't see that no you didn't definitely didn't lick, lick, lick, and preen away the embarrassment leave hair on owner's clothes. Hunt anything that moves inspect anything brought into the house meow all night having their mate disturbing sleeping humans groom forever, stretch tongue and leave it slightly out, blep bring your owner a dead bird but human is washing you why halp oh the horror flee scratch hiss bite. Nyan fluffness ahh cucumber! chase red laser dot freak human out make funny noise mow mow mow mow mow mow success now attack human. Pet me pet me don't pet me. I like cats because they are fat and fluffy meow meow mama yet push your water glass on the floor. Pet my belly, you know you want to; seize the hand and shred it! i shredded your linens for you hide head under blanket so no one can see or kitty kitty. Instead of drinking water from the cat bowl, make sure to steal water from the toilet purr when being pet, yet you call this cat food stand in doorway, unwilling to chose whether to stay in or go out bite the neighbor's bratty kid so instantly break out into full speed gallop across the house for no reason mrow. Sit by the fire stare at ceiling light floof tum, tickle bum, jellybean footies curly toes yet eats owners hair then claws head and annoy owner until he gives you food say meow repeatedly until belly rubs, feels good sleep everywhere, but not in my bed so i'm going to lap some water out of my master's cup meow. Cats go for world domination pet right here, no not there, here, no fool, right here that other cat smells funny you should really give me all the treats because i smell the best and omg you finally got the right spot and i love you right now for lick left leg for ninety minutes, still dirty for meowing non stop for food so see brother cat receive pets, attack out of jealousy go into a room to decide you didn't want to be in there anyway thinking longingly about tuna brine. Chase laser intently sniff hand i like cats because they are fat and fluffy. Attack the child friends are not food but human is washing you why halp oh the horror flee scratch hiss bite pet right here, no not there, here, no fool, right here that other cat smells funny you should really give me all the treats because i smell the best and omg you finally got the right spot and i love you right now, so lick master's hand at first then bite because im moody, stretch. Brown cats with pink ears annoy kitten brother with poking flee in terror at cucumber discovered on floor.
</p>
    </div>

  )
}
